name: Build and deploy Node.js app to Azure Web App - Ecom

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install client dependencies and build
        run: |
          cd client
          npm ci
          npm run build

      - name: Install admin dependencies and build
        run: |
          cd admin
          npm ci
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Copy builds to server/public
        run: |
          mkdir -p server/public/app
          mkdir -p server/public/admin
          cp -r client/dist/* server/public/app/
          cp -r admin/dist/* server/public/admin/

      - name: Create web.config for Azure App Service (Windows only)
        run: |
          cat <<EOT > server/web.config
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="DynamicContent">
                    <match url=".*" />
                    <action type="Rewrite" url="index.js"/>
                  </rule>
                </rules>
              </rewrite>
              <iisnode watchedFiles="*.js;node_modules\\*" nodeProcessCommandLine="node.exe" />
            </system.webServer>
          </configuration>
          EOT

      - name: Zip deployment package
        run: |
          cd server
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: release
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Ecom"
          package: release.zip
