name: Build and deploy Node.js app to Azure Web App - SmartEcart

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_ENV: production
  WEBSITE_NODE_DEFAULT_VERSION: '20-lts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          npm run build --if-present
          # Ensure the server files are properly structured
          mkdir -p server-build
          cp -r server/* server-build/
          cp package.json server-build/

      - name: Create deployment package
        run: |
          cd server-build && zip -r ../release.zip ./*
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip package
        run: unzip release.zip -d deployment-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C6293E2CF044177A7743A13946B94CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F80D5EA40E3B4EE9B55C6E12A6AD5D84 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDF609657E0740BE9339F398DFD5CC9E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SmartEcart'
          slot-name: 'Production'
          package: 'deployment-package'
          clean: true
          scm-type: none