name: Build and Deploy Node.js App to Azure Web App - SmartEcart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build apps (client, admin, server)
        run: npm run build

      - name: Zip server directory for deployment
        run: |
          cd server
          zip -r ../release.zip .
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-server-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-server-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBDDAFAA241947DE87589DAD973B526B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A764A1BDF02B4B43B2C86284A6312AFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DF2A31850F8B4C55A777C4955870C0CE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SmartEcart'
          slot-name: 'Production'
          package: release.zip
